spring.main.sources: dk.dma.enav.integrations.TilerServiceRouter

server.port: 9081

tiles.daysToKeep: -1

tracing: true

mapTiler.arguments:

tiles.server.port: 8080

---
spring:
  profiles: unittest


tiles.daysToKeep: 10

tiles.localDirectory: target/test-classes/tilesOld