spring.main.sources: dk.dma.enav.integrations.TilerServiceRouter

server.port: 9081

# to be implemented later
tiles.maxConcurrentJobs: 1

dmi.daysToKeep: -1

tiles.daysToKeep: -1

tracing: true

mapTiler.arguments:

---
spring:
  profiles: unittest

dmi.server: 127.0.0.1

dmi.directory:

dmi.user: user

dmi.password: password

dmi.daysToKeep: 60

tiles.daysToKeep: 10

tiles.localDirectory: target/test-classes/tilesOld